### ISSUE TITLE
Calling `.leave()` during audio playing blocks audio playing on reconnection

### ISSUE THREAD

**Issue by JellyWX** [serenity-rs/songbird#56]
When calling `.leave()` on a Call, if that call is already playing audio and the `.leave()` interrupts it, then upon rejoining the call, the bot will not play audio.

Calling `.remove()` instead to drop the call is fine

**Comment by FelixMcFelix** [comment]
I updated my main bot to 0.1.5 (since I was awaiting a serenity version update) and have quickly repro'd and confirmed. I have a feeling this was introduced by #46.

**Comment by DoumanAsh** [comment]
I encountered similar situation with `remove`
If I call `Call::stop` and then `Songbird::remove`  ~and then attempt to reconnect using `Songbird::join`~
```
thread '<unnamed>' panicked at 'Shouldn't be mixing packets without access to a cipher + UDP dest.', C:\Users\Douman\data\Soft\Dev\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\songbird-0.1.5\src\driver\tasks\mixer.rs:492:14
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
   2: core::option::expect_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\option.rs:1292
   3: core::option::Option<mut songbird::driver::tasks::message::mixer::MixerConnection*>::expect<mut songbird::driver::tasks::message::mixer::MixerConnection*>
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\core\src\option.rs:349
   4: songbird::driver::tasks::mixer::Mixer::prep_and_send_packet
             at C:\Users\Douman\data\Soft\Dev\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\songbird-0.1.5\src\driver\tasks\mixer.rs:489
   5: songbird::driver::tasks::mixer::Mixer::cycle
             at C:\Users\Douman\data\Soft\Dev\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\songbird-0.1.5\src\driver\tasks\mixer.rs:478
   6: songbird::driver::tasks::mixer::Mixer::run
             at C:\Users\Douman\data\Soft\Dev\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\songbird-0.1.5\src\driver\tasks\mixer.rs:135
   7: songbird::driver::tasks::mixer::runner
             at C:\Users\Douman\data\Soft\Dev\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\songbird-0.1.5\src\driver\tasks\mixer.rs:629
   8: songbird::driver::tasks::start_internals::{{closure}}
             at C:\Users\Douman\data\Soft\Dev\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\songbird-0.1.5\src\driver\tasks\mod.rs:54
```

It becomes ok if I invoke `TrackHandle::stop`

**Comment by FelixMcFelix** [comment]
I think I've figured out what the issue was: if you get the chance to confirm with [this branch](https://github.com/FelixMcFelix/songbird/tree/fix-driver-leave-join) then that'd be great. 😄

**Comment by JellyWX** [comment]
Seems fixed to me, thanks! :)
